### ISSUE TITLE
NoSuchAlgorithmException in Client and Server

### ISSUE THREAD

**Issue by skiunke** [williamswhy/SSLSocket#5]
Hey,
thanks for the recent commit. 

Unfortunately  i can't get it to work now. 
On both ends (server and client) I get the following exception: 

```
java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at java.base/javax.net.ssl.DefaultSSLServerSocketFactory.throwException(SSLServerSocketFactory.java:177)
	at java.base/javax.net.ssl.DefaultSSLServerSocketFactory.createServerSocket(SSLServerSocketFactory.java:190)
	at Server.<init>(Server.java:18)
	at Server.main(Server.java:34)
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1900)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:184)
	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:110)
	at java.base/javax.net.ssl.SSLServerSocketFactory.getDefault(SSLServerSocketFactory.java:74)
	at Server.<init>(Server.java:17)
	... 1 more
Caused by: java.security.KeyManagementException
	at java.base/sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:942)
	at java.base/sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:1112)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at java.base/java.security.Provider.newInstanceUtil(Provider.java:155)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1893)
	... 7 more
```
I downloaded the sslclienttrust and sslserverkeys from one of your previous commits. 
I initialized them like this: 
In Server: 
```
System.setProperty("javax.net.ssl.keyStore", "sslserverkeys");
System.setProperty("javax.net.ssl.keyStorePassword", "123456");
```
In Client: 
```
System.setProperty("javax.net.ssl.trustStore", "sslclienttrust");
System.setProperty("javax.net.ssl.trustStorePassword", "123456");
```

With your recent readme i can't figure out how to create the required files for client and server.
Could you @mention some information about the proccess, if you're not updating this repo anymore. 

Thanks in advance :)

**Comment by williamswhy** [comment]
The trust and key files from previous commits are not valid anymore. They were generated by the old default algorithm in `keytool` which is DSA but `RSA` is needed now. You can try the steps to generate keys in the readme fine under `bin` folder. Let me know if it works for you!

**Comment by williamswhy** [comment]
I just walked through the README myself. I think the steps are correct. Let me know if you find any problem. Thank you!

**Comment by skiunke** [comment]
Unfortunately this didn't work. 
I followed the readme guide on 7be23ce
I had to add the -keyalg RSA to generate. 

```
keytool -genkey -alias sslclient -keystore sslclientkeys
Export client keystore as certification

keytool -export -alias sslclient -keystore sslclientkeys -file sslclient.cer
Create a server keystore file

keytool -genkey -alias sslserver -keystore sslserverkeys
Import client's certification into server's truststore

keytool -import -alias sslclient -keystore sslservertrust -file sslclient.cer 
Import server's certification into client's truststore

keytool -import -alias sslserver -keystore sslclienttrust -file sslserver.cer 
To view your keystore or trust

keytool -list -keystore sslclienttrust
```
(The export of the server keystore as certification command is missing)
Am i missing something? Do i need to add them to the lib/security/cacerts ?

**Comment by williamswhy** [comment]
The latest README is in the current master branch. The one you have is an older version.

**Comment by skiunke** [comment]
Used this: 
```
Create a server keystore file:

keytool -genkey -keystore sslserverkeys -keyalg RSA
Export the key as a cert:

keytool -export -keystore sslserverkeys -file cert.cer -keyalg RSA
Add the cert to the trust store of the client:

keytool -import -keystore sslclienttrust -file cert.cer -keyalg RSA
```

then i copied them into my src folder.  Same error message

in Server: 
 System.setProperty("javax.net.ssl.keyStore", "sslserverkeys");
 System.setProperty("javax.net.ssl.keyStorePassword", "123456");

in Client: 
 System.setProperty("javax.net.ssl.trustStore", "sslclientkeys");
 System.setProperty("javax.net.ssl.trustStorePassword", "123456");

**Comment by williamswhy** [comment]
I can reproduce this problem on the client-side if the password is wrong. On the server-side, I got `NullPointerException`. I am not really sure how you got both ends to throw this error.
With that being said, I usually put my SSL files in whichever folder I run the programs from (If you follow the commands in README, it should be the `bin` folder) so if you did not run the program from `src`, it might cause the issue.

**Comment by skiunke** [comment]
This fixed the issue.
I moved the sslclienttrust and sslserverkeys to the main folder and call them with src/main/...
